version: 2

updates:

 # Enable version updates for Docker
  - package-ecosystem: "docker"
    target-branch: "php8.3"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "*"
        update-types: [ "version-update:semver-minor" ]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "php8.3"
    directory: "/"
    schedule:
      interval: "daily"