version: 2

updates:

 # Enable version updates for Docker
  - package-ecosystem: "docker"
    target-branch: "php8.1"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*fpm-alpine*"
        # For Express, ignore all updates for version 4 and 5
        versions: ["8.2.x-fpm-alpine3.16"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "php8.1"
    directory: "/"
    schedule:
      interval: "daily"